language: python

python:
  - "3.8"

addons:
  apt:
    packages:
      - libopenmpi-dev
      - openmpi-bin

install:
  pip install matplotlib
  pip install scipy
  pip install argparse
  pip install numba
  pip install sympy
  pip install mpi4py
  pip install tikzplotlib

script:
  - export PYTHONPATH=$(pwd)
  - python3.8 tests/test_script.py
