language: python
python:
  - "3.8"
addons:
  apt:
    packages:
      - libopenmpi-dev
      - openmpi-bin
install:
  pip install -r tests/requirements.txt
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - python3.8 tests/test_script.py
