# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test of published calculations

on:
  push:
    branches: [ master ]
    
jobs:
  build:

    runs-on: self-hosted
    timeout-minutes: 1440

    steps:
    - uses: actions/checkout@v3.0.2
    - name: Run test script
      run:  python3 tests/test_script.py --path published_calculations --latex False --mpin 1
